import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'
import { build_rules_sidebar } from './sidebar.mts'

// Resolve `docs/rules/` relative to this config file so the sidebar generator
// works regardless of the cwd VitePress is invoked from.
const rules_dir = fileURLToPath(new URL('../rules', import.meta.url))

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'hlsl-clippy',
  description:
    'Linter for HLSL — performance + correctness rules beyond what dxc catches',

  // GitHub Pages project page lives at https://nelcit.github.io/hlsl-clippy/.
  // The trailing slash on `base` is required by VitePress for asset paths.
  base: '/hlsl-clippy/',

  cleanUrls: true,
  lastUpdated: true,

  // Skip the ADR brainstorm scratch folder — those notes contain unescaped
  // `<T>` / `<expected>` angle-bracket text that Vue's SFC parser misreads as
  // unclosed HTML tags. Not intended for the public docs site anyway.
  srcExclude: [
    '**/_research/**',
    '**/_template.md',
    '**/AGENTS.md',
    // ADRs contain GitHub Actions `${{ runner.os }}` expressions inside
    // markdown tables that Vue's SSR misinterprets as template bindings.
    // ADRs live in the repo and are linked from CONTRIBUTING/ROADMAP via
    // GitHub URLs, not the public docs site.
    'decisions/**',
  ],

  // Some rule pages cross-link to siblings that haven't been authored yet
  // (e.g. `./samplecmp-without-comparison-sampler`) and a few link to
  // `./../../ROADMAP` which lives at the repo root, not on the docs site.
  // Ship the launch with these tolerated; the catalog still surfaces every
  // rule via the autogenerated sidebar. Tidy follow-up tracked for v0.6.
  ignoreDeadLinks: [
    // Repo-root files (CHANGELOG / CONTRIBUTING / ROADMAP) referenced from
    // rule pages — they live in the repo, not on the docs site. Clean
    // resolution is a v0.6 polish task (rewrite to GitHub absolute URLs).
    /(ROADMAP|CONTRIBUTING|CHANGELOG)$/,
    // Blog post → rules cross-link uses the wrong relative depth.
    /\/rules\/pow-const-squared$/,
    // Sibling rules referenced in cross-link sections that haven't been
    // authored yet — listed in ROADMAP.md and tracked for a later pack.
    /(samplecmp-without-comparison-sampler|shadow-bias-too-small|unused-vs-output|discard-after-heavy-work|redundant-rcp-mul)$/,
  ],

  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Rules', link: '/rules/' },
      { text: 'Blog', link: '/blog/' },
      { text: 'Roadmap', link: '/roadmap' },
      {
        text: 'GitHub',
        link: 'https://github.com/NelCit/hlsl-clippy',
      },
    ],

    sidebar: {
      '/rules/': build_rules_sidebar(rules_dir),

      '/blog/': [
        {
          text: 'Blog',
          items: [
            { text: 'Index', link: '/blog/' },
            {
              text: 'Posts',
              items: [
                {
                  text: 'pow(x, 2.0) is hiding a transcendental in your shader',
                  link: '/blog/pow-const-squared',
                },
              ],
            },
          ],
        },
      ],

      '/': [
        {
          text: 'Documentation',
          items: [
            { text: 'Getting started', link: '/getting-started' },
            { text: 'Configuration', link: '/configuration' },
            { text: 'Architecture', link: '/architecture' },
            { text: 'CI integration', link: '/ci' },
            { text: 'LSP / IDE', link: '/lsp' },
            { text: 'Contributing', link: '/contributing' },
          ],
        },
        {
          text: 'Project',
          items: [
            { text: "What's new", link: '/changelog' },
            { text: 'Roadmap', link: '/roadmap' },
          ],
        },
      ],
    },

    outline: [2, 3],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/NelCit/hlsl-clippy' },
    ],

    editLink: {
      pattern: 'https://github.com/NelCit/hlsl-clippy/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: '© 2026 NelCit — Apache-2.0 (code), CC-BY-4.0 (docs).',
      copyright: '',
    },

    search: {
      provider: 'local',
    },
  },
})
