import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'
import { build_rules_sidebar } from './sidebar.mts'

// Resolve `docs/rules/` relative to this config file so the sidebar generator
// works regardless of the cwd VitePress is invoked from.
const rules_dir = fileURLToPath(new URL('../rules', import.meta.url))

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'hlsl-clippy',
  description:
    'Linter for HLSL — performance + correctness rules beyond what dxc catches',

  // GitHub Pages project page lives at https://nelcit.github.io/hlsl-clippy/.
  // The trailing slash on `base` is required by VitePress for asset paths.
  base: '/hlsl-clippy/',

  cleanUrls: true,
  lastUpdated: true,

  // Sitemap: lets crawlers discover every page without spidering. Hostname
  // matches the GitHub Pages project page (must include the `/hlsl-clippy/`
  // base path; sitemap URLs auto-derive from `base`).
  sitemap: {
    hostname: 'https://nelcit.github.io/hlsl-clippy/',
  },

  // Social-card meta for HN / Reddit / Twitter / Discord previews. The
  // tagline mirrors the README's pitch; leaving og:image unset for now —
  // VitePress will fall back to the favicon.
  head: [
    ['meta', { name: 'description', content: 'Linter for HLSL — 154 portable performance + correctness rules beyond what dxc catches.' }],
    ['meta', { property: 'og:title', content: 'hlsl-clippy' }],
    ['meta', { property: 'og:description', content: 'Linter for HLSL — 154 portable performance + correctness rules beyond what dxc catches.' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:url', content: 'https://nelcit.github.io/hlsl-clippy/' }],
    ['meta', { name: 'twitter:card', content: 'summary' }],
    ['meta', { name: 'twitter:title', content: 'hlsl-clippy' }],
    ['meta', { name: 'twitter:description', content: 'Linter for HLSL — 154 portable performance + correctness rules beyond what dxc catches.' }],
  ],

  // Skip the ADR brainstorm scratch folder — those notes contain unescaped
  // `<T>` / `<expected>` angle-bracket text that Vue's SFC parser misreads as
  // unclosed HTML tags. Not intended for the public docs site anyway.
  srcExclude: [
    '**/_research/**',
    '**/_template.md',
    '**/AGENTS.md',
    // ADRs contain GitHub Actions `${{ runner.os }}` expressions inside
    // markdown tables that Vue's SSR misinterprets as template bindings.
    // ADRs live in the repo and are linked from CONTRIBUTING/ROADMAP via
    // GitHub URLs, not the public docs site.
    'decisions/**',
  ],

  // Some rule pages cross-link to siblings that haven't been authored yet
  // (e.g. `./samplecmp-without-comparison-sampler`) and a few link to
  // `./../../ROADMAP` which lives at the repo root, not on the docs site.
  // Ship the launch with these tolerated; the catalog still surfaces every
  // rule via the autogenerated sidebar. Tidy follow-up tracked for v0.6.
  ignoreDeadLinks: [
    // Repo-root files (CHANGELOG / CONTRIBUTING / ROADMAP) referenced from
    // rule pages — they live in the repo, not on the docs site. Clean
    // resolution is a v0.6 polish task (rewrite to GitHub absolute URLs).
    /(ROADMAP|CONTRIBUTING|CHANGELOG)$/,
    // Blog post → rules cross-link uses the wrong relative depth.
    /\/rules\/pow-const-squared$/,
    // Sibling rules referenced in cross-link sections that haven't been
    // authored yet — listed in ROADMAP.md and tracked for a later pack.
    /(samplecmp-without-comparison-sampler|shadow-bias-too-small|unused-vs-output|discard-after-heavy-work|redundant-rcp-mul)$/,
    // The 205 v1.0.0 stub blog posts each link to `../decisions/0018-...md`
    // (and a couple of stubs to other ADRs). `srcExclude: ['decisions/**']`
    // above keeps ADRs off the docs site (they have `${{ runner.os }}`
    // expressions that confuse Vue's SSR), so every blog → decision link is
    // dead from VitePress's perspective. The link still resolves on
    // GitHub.com where the files live; tolerate them on the rendered site.
    /\/decisions\/\d{4}-/,
  ],

  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Rules', link: '/rules/' },
      { text: 'Blog', link: '/blog/' },
      { text: 'Roadmap', link: '/roadmap' },
      {
        text: 'GitHub',
        link: 'https://github.com/NelCit/hlsl-clippy',
      },
    ],

    sidebar: {
      '/rules/': build_rules_sidebar(rules_dir),

      '/blog/': [
        {
          text: 'Blog',
          items: [{ text: 'Index', link: '/blog/' }],
        },
        {
          text: 'v0.5.0 launch series',
          collapsed: false,
          items: [
            {
              text: 'Why your HLSL is slower than it has to be',
              link: '/blog/why-your-hlsl-is-slower-than-it-has-to-be',
            },
            { text: 'Math intrinsics', link: '/blog/math-overview' },
            { text: 'Workgroup / groupshared', link: '/blog/workgroup-overview' },
            { text: 'Control flow + divergence', link: '/blog/control-flow-overview' },
            { text: 'Bindings + root signature', link: '/blog/bindings-overview' },
            { text: 'Texture + sampler', link: '/blog/texture-overview' },
            { text: 'Mesh shaders + DXR', link: '/blog/mesh-dxr-overview' },
            { text: 'Wave + helper-lane', link: '/blog/wave-helper-lane-overview' },
            { text: 'SM 6.9: SER, coop-vec, long-vec, OMM', link: '/blog/ser-coop-vector-overview' },
          ],
        },
        {
          text: 'Per-rule deep dives',
          collapsed: true,
          items: [
            {
              text: 'pow(x, 2.0) is hiding a transcendental in your shader',
              link: '/blog/pow-const-squared',
            },
          ],
        },
      ],

      '/': [
        {
          text: 'Documentation',
          items: [
            { text: 'Getting started', link: '/getting-started' },
            { text: 'Configuration', link: '/configuration' },
            { text: 'Architecture', link: '/architecture' },
            { text: 'CI integration', link: '/ci' },
            { text: 'LSP / IDE', link: '/lsp' },
            { text: 'Troubleshooting', link: '/troubleshooting' },
            { text: 'Contributing', link: '/contributing' },
          ],
        },
        {
          text: 'Project',
          items: [
            { text: "What's new", link: '/changelog' },
            { text: 'Roadmap', link: '/roadmap' },
          ],
        },
      ],
    },

    outline: [2, 3],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/NelCit/hlsl-clippy' },
    ],

    editLink: {
      pattern: 'https://github.com/NelCit/hlsl-clippy/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: '© 2026 NelCit — Apache-2.0 (code), CC-BY-4.0 (docs).',
      copyright: '',
    },

    search: {
      provider: 'local',
    },
  },
})
