# tools/fp-rate-baseline.ps1
#
# Aggregates per-rule firing counts across `tests/corpus/` to produce the
# v1.0 readiness criterion #3 baseline (`tests/corpus/FP_RATES.md`). Per
# ADR 0018 §5: every warn-severity rule carries a measured FP rate
# <= 5% against the corpus.
#
# This script is the *firing-count* baseline. Triage of TP vs FP is a
# human-judgement step: each diagnostic is reviewed by a maintainer
# against the rule's "Why it matters on a GPU" and either marked TP
# (rule was right; the corpus shader is a real instance of the
# anti-pattern) or FP (rule fired on a false positive). The output
# table has a TODO column for that triage; FP rate = FP / (TP + FP)
# per rule.
#
# Usage (from repo root):
#   pwsh tools\fp-rate-baseline.ps1
#
# Output: tests/corpus/FP_RATES.md (overwritten each run).

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir
$CliPath   = Join-Path $RepoRoot 'build\cli\shader-clippy.exe'
$CorpusDir = Join-Path $RepoRoot 'tests\corpus'
$OutputMd  = Join-Path $CorpusDir 'FP_RATES.md'

if (-not (Test-Path -LiteralPath $CliPath)) {
    Write-Error "fp-rate-baseline: cli not found at $CliPath. Run cmake --build build first."
    exit 1
}

# Recursively enumerate every .hlsl under tests/corpus/ (excluding
# SOURCES.md and any nested build artifacts).
$shaders = Get-ChildItem -LiteralPath $CorpusDir -Recurse -Filter '*.hlsl' |
    Where-Object { -not $_.PSIsContainer } |
    Sort-Object FullName

Write-Host "fp-rate-baseline: scanning $($shaders.Count) shader(s) under $CorpusDir"

# rule-id -> [{ shader, line, severity }]
$findings = @{}

foreach ($sh in $shaders) {
    $rel = $sh.FullName.Substring($RepoRoot.Length + 1).Replace('\', '/')
    Write-Host "  - $rel"

    # The CLI returns non-zero when diagnostics fire, which PowerShell
    # treats as an error. Capture the JSON output regardless of exit code.
    $json = & $CliPath lint --format=json $sh.FullName 2>$null
    if ([string]::IsNullOrWhiteSpace($json)) {
        continue
    }

    try {
        $diags = $json | ConvertFrom-Json
    } catch {
        Write-Warning "  ! cannot parse JSON for $rel"
        continue
    }

    if ($diags -isnot [array]) {
        $diags = @($diags)
    }

    foreach ($d in $diags) {
        if (-not $d.PSObject.Properties['rule']) { continue }
        $rule = $d.rule
        if (-not $findings.ContainsKey($rule)) {
            $findings[$rule] = New-Object System.Collections.ArrayList
        }
        [void]$findings[$rule].Add(@{
            shader   = $rel
            line     = $d.line
            severity = $d.severity
        })
    }
}

# --- Render the markdown table -------------------------------------------

$header = @"
# Corpus FP-rate baseline (v1.0 readiness criterion #3)

This file is the per-rule firing-count baseline against ``tests/corpus/``
(see [tests/corpus/SOURCES.md](SOURCES.md) for the per-shader registry).
Per [ADR 0018 §5 criterion #3](../../docs/decisions/0018-v08-research-direction.md):
every warn-severity rule must carry a measured FP rate <= 5% against
the corpus before v1.0 ships.

The ``Triage`` column is the human-judgement step: each rule's firings
are reviewed against the rule's ``Why it matters on a GPU`` body and
classified ``TP`` (true positive — corpus shader genuinely exhibits
the anti-pattern) or ``FP`` (false positive — rule misfired). Rules
with mixed firings get a fraction (``5 TP / 1 FP`` for example).

This file is regenerated by ``pwsh tools/fp-rate-baseline.ps1`` after
each release. The ``Triage`` column is preserved across runs only when
the rule's firing count is unchanged; otherwise the maintainer re-triages.

| Rule | Total firings | Shaders affected | Triage | FP rate |
|------|---------------|------------------|--------|---------|
"@

$rows = @()
$rules = $findings.Keys | Sort-Object
foreach ($rule in $rules) {
    $count = $findings[$rule].Count
    $shaderSet = $findings[$rule] | ForEach-Object { $_.shader } | Sort-Object -Unique
    $shaderCount = ($shaderSet | Measure-Object).Count
    $rows += "| ``$rule`` | $count | $shaderCount | TODO | TODO |"
}

if ($rows.Count -eq 0) {
    $rows = @('| _(no diagnostics fired against the corpus)_ | 0 | 0 | — | — |')
}

$footer = @"

## Summary

- Rules with at least one corpus firing: $(($findings.Keys | Measure-Object).Count) of 190.
- Total diagnostics: $((($findings.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum) -as [int]).
- Corpus shaders scanned: $($shaders.Count).

Re-run via ``pwsh tools/fp-rate-baseline.ps1``; commit the regenerated
file alongside the ``Triage`` column updates.
"@

$body = ($header, "") + $rows + ("", $footer)
Set-Content -LiteralPath $OutputMd -Value ($body -join "`n") -Encoding UTF8

Write-Host "fp-rate-baseline: wrote $OutputMd"
Write-Host "  rules with firings: $(($findings.Keys | Measure-Object).Count)"
Write-Host "  total diagnostics : $((($findings.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum) -as [int])"
